### ISSUE TITLE
iocs directory needs work

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADPcoWin#1]
I have created an iocs directory containing an example IOC.  It builds the pcocam2App application.  There is an iocBoot/iocPcocam2 directory with an st.cmd file that creates a detector instance.  However, I don't know what databases it should load and what else it should do.

@ulrikpedersen can someone at Diamond fix and test the st.cmd file?

**Comment by BenBradnick** [comment]
I can take a look at this.

**Comment by MarkRivers** [comment]
It looks like Ben undid a number of my changes.

My iocs/pcocam2IOC/configure/RELEASE file looks like this:
```
corvette:iocs/pcocam2IOC/configure>more RELEASE
#RELEASE Location of external products
# Run "gnumake clean uninstall install" in the application
# top directory each time this file is changed.

ADPCOWIN=$(TOP)/../..

-include $(TOP)/../../../configure/RELEASE_PRODS_INCLUDE
-include $(TOP)/RELEASE.local
-include $(TOP)/configure/RELEASE.local
```
But that got replaced by one that Oksana had to change back to what I had.

**Comment by BenBradnick** [comment]
Hi Mark - I apologise for this mess. I was having issues with running the IOC at our end - I shouldn't have committed the changes to this file.

**Comment by BenBradnick** [comment]
I believe this issue has been resolved and can be closed.

**Comment by MarkRivers** [comment]
Closing this.
